### PR TITLE
Sign in/yasu

### PR DESCRIPTION
**Pull request by ymiura89**
PR for Sign-In Page

### CODE REVIEW

**Comment by ymiura89** [comment]
Okay, I think I got it now.

**Comment by chrisxadvocatus** [comment]
Good work! Let's work on these two things: 
- importing images 
- put sign up page in a js file
See slack message for more info.

**Comment by ymiura89** [comment]
I believe I set up the Sign up page with React the same way Anthony and I did the Sign in page. Also, logo image should be importing.

**Comment by chrisxadvocatus** [comment]
Convert to draft. Waiting for bugs to be resolved

**Pull request closed without merging**
